import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import type { Category } from "../src/lib/categories";
import { componentEntrySchema } from "../src/schemas/component-entry";
import { readIdeaPool, writeIdeaPool } from "./lib/idea-pool";

type Difficulty = "beginner" | "intermediate" | "advanced";

type Seed = {
  slug: string;
  title: string;
  category: Category;
  tags: string[];
  difficulty: Difficulty;
  visual: string;
  interaction: string;
  motion: string;
  createdAt?: string;
};

const seeds: Seed[] = [
  { slug: "magnetic-glow-button", title: "Magnetic Glow Button", category: "buttons", tags: ["magnetic", "glow", "cta"], difficulty: "intermediate", visual: "a compact near-black call-to-action with a lime status dot, crisp white label, and a restrained cyan halo that feels magnetic rather than neon-heavy", interaction: "the control lifts toward the pointer, compresses on press, and keeps a clearly visible keyboard focus ring", motion: "use a spring with stiffness 300 and damping 24 for hover movement, plus a 140ms press response" },
  { slug: "liquid-fill-button", title: "Liquid Fill Button", category: "buttons", tags: ["liquid", "fill", "hover"], difficulty: "intermediate", visual: "a white pill button with a black outline and a solid lemon layer resting below the label", interaction: "the lemon layer rises from the bottom on hover or focus while the label changes contrast and remains readable", motion: "animate the fill over 420ms with cubic-bezier(0.22, 1, 0.36, 1), then use a 120ms tap scale" },
  { slug: "ripple-confirm-button", title: "Ripple Confirm Button", category: "buttons", tags: ["ripple", "confirmation", "microinteraction"], difficulty: "beginner", visual: "a rounded orange action button with a small circular confirmation indicator and strong black typography", interaction: "pressing creates a centered ripple impression and changes the indicator into a settled success state without moving surrounding layout", motion: "use a 180ms press, a 520ms ripple expansion with ease-out, and a spring check transition at stiffness 360 damping 22" },
  { slug: "tilt-spotlight-card", title: "Tilt Spotlight Card", category: "cards", tags: ["tilt", "spotlight", "depth"], difficulty: "advanced", visual: "a pale gray product card with a cyan spotlight disc, a compact category pill, and a large editorial number", interaction: "the card tilts subtly toward the pointer while the spotlight shifts inside its bounds and returns smoothly on leave", motion: "limit rotation to four degrees and use stiffness 300 damping 24 for the return spring" },
  { slug: "expandable-metric-card", title: "Expandable Metric Card", category: "cards", tags: ["metrics", "expand", "dashboard"], difficulty: "intermediate", visual: "a clean analytics tile with a 64px metric, lime delta pill, miniature bars, and generous white space", interaction: "hover expands the chart region and reveals a concise comparison label without causing a surrounding layout shift", motion: "use a 320ms ease-out reveal and stagger bars by 40ms" },
  { slug: "stacked-profile-card", title: "Stacked Profile Card", category: "cards", tags: ["profiles", "stack", "social"], difficulty: "beginner", visual: "three offset profile sheets using pink, purple, and white surfaces with circular initials and concise role labels", interaction: "hover fans the sheets apart, raises the front card, and preserves readable stacking on touch devices", motion: "use a spring at stiffness 280 damping 25 with 50ms stagger between sheets" },
  { slug: "floating-label-input", title: "Floating Label Input", category: "inputs", tags: ["form", "floating-label", "focus"], difficulty: "beginner", visual: "a spacious white input inside a soft gray panel with a compact label that floats above the typed value", interaction: "focus moves and scales the label, strengthens the border, and shows helper text without changing the field height", motion: "use a 180ms ease-out label transition and a 220ms focus-ring fade" },
  { slug: "otp-wave-input", title: "OTP Wave Input", category: "inputs", tags: ["otp", "verification", "wave"], difficulty: "intermediate", visual: "six individual rounded code cells with alternating cyan and lime accents and a restrained monospace treatment", interaction: "focus advances through cells, completed values rise in a small wave, and paste remains supported", motion: "stagger settled cells by 45ms using a stiffness 340 damping 23 spring" },
  { slug: "command-search-input", title: "Command Search Input", category: "inputs", tags: ["search", "command-menu", "keyboard"], difficulty: "intermediate", visual: "a wide search field with a magnifier, muted placeholder, and a small Command K keycap on the right", interaction: "focus expands the field slightly, reveals two suggestion rows, and supports arrow-key selection with a visible active option", motion: "use a 240ms ease-out panel reveal and 40ms stagger for results" },
  { slug: "morphing-pill-nav", title: "Morphing Pill Navigation", category: "navigation", tags: ["tabs", "pill", "active-state"], difficulty: "intermediate", visual: "a compact white navigation rail where the active item sits on a solid lime capsule", interaction: "the active capsule glides between labels while hover states remain subtle and keyboard focus stays independent", motion: "use a shared-layout spring with stiffness 320 damping 28 and no opacity crossfade" },
  { slug: "dock-magnifier-nav", title: "Dock Magnifier Navigation", category: "navigation", tags: ["dock", "magnification", "icons"], difficulty: "advanced", visual: "a near-black floating dock with five rounded square icons and one cyan notification dot", interaction: "icons nearest the pointer enlarge and lift while distant icons remain stable; keyboard focus provides the same emphasized state", motion: "use stiffness 300 damping 24 and cap scale at 1.35" },
  { slug: "breadcrumb-progress-nav", title: "Breadcrumb Progress Navigation", category: "navigation", tags: ["breadcrumb", "progress", "steps"], difficulty: "beginner", visual: "a three-step breadcrumb with numbered circles, compact labels, and a lemon progress connector", interaction: "completed steps appear solid, the current step pulses once, and links retain generous hit areas", motion: "animate the connector over 500ms with ease-in-out and the current marker with a 260ms spring" },
  { slug: "orbit-dot-loader", title: "Orbit Dot Loader", category: "loaders", tags: ["orbit", "loading", "dots"], difficulty: "beginner", visual: "three small cyan, lime, and orange dots orbiting a quiet central black disc", interaction: "the loop communicates indeterminate progress without flashing or sudden acceleration", motion: "use a 1.4 second linear orbit with evenly offset phases and honor reduced motion" },
  { slug: "elastic-bar-loader", title: "Elastic Bar Loader", category: "loaders", tags: ["bars", "elastic", "loading"], difficulty: "beginner", visual: "five rounded black bars on a lemon tile, varying in height like an audio equalizer", interaction: "bars stretch from their center in a continuous but calm elastic sequence", motion: "use 800ms ease-in-out loops with 70ms stagger and alternate direction" },
  { slug: "skeleton-shimmer-loader", title: "Soft Skeleton Loader", category: "loaders", tags: ["skeleton", "shimmer", "content"], difficulty: "beginner", visual: "an editorial card skeleton built from neutral gray blocks plus a small solid pink thumbnail placeholder", interaction: "a low-contrast highlight travels across the neutral blocks without obscuring their shapes", motion: "use a 1.6 second linear pass and disable movement under reduced-motion preferences" },
  { slug: "kinetic-type-reveal", title: "Kinetic Type Reveal", category: "text-effects", tags: ["typography", "reveal", "stagger"], difficulty: "intermediate", visual: "the word BUILD set in oversized tight black capitals with a cyan punctuation mark", interaction: "letters rise and unmask in sequence when the component enters or is replayed", motion: "use 420ms ease-out per character with 45ms stagger and no blur" },
  { slug: "split-flap-counter", title: "Split Flap Counter", category: "text-effects", tags: ["counter", "split-flap", "numbers"], difficulty: "advanced", visual: "four near-black mechanical number tiles with white monospace digits and a thin horizontal hinge line", interaction: "digits flip forward to the next value while the card dimensions remain fixed", motion: "use a 480ms perspective rotation with cubic-bezier(0.2, 0.8, 0.2, 1) and 60ms stagger" },
  { slug: "scramble-text-reveal", title: "Scramble Text Reveal", category: "text-effects", tags: ["scramble", "decode", "terminal"], difficulty: "intermediate", visual: "a compact system label where muted random glyphs resolve into a sharp final phrase beside a lime dot", interaction: "replay cycles through readable-length placeholders and settles without shifting width", motion: "resolve characters over 900ms with 35ms steps and stop entirely for reduced motion" },
  { slug: "cursor-dot-grid", title: "Cursor Dot Grid", category: "backgrounds", tags: ["cursor", "grid", "ambient"], difficulty: "advanced", visual: "a white field of tiny gray dots with a localized cluster turning cyan near the interaction point", interaction: "nearby dots scale gently with pointer proximity while the background itself never scroll-jacks", motion: "use 160ms interpolation and cap dot scale at 1.8" },
  { slug: "paper-noise-grid", title: "Paper Noise Grid", category: "backgrounds", tags: ["paper", "grid", "texture"], difficulty: "beginner", visual: "a warm off-white paper surface combining hairline gray rules, sparse black registration marks, and one lemon note", interaction: "the note lifts slightly on hover while the texture remains static and distraction-free", motion: "use a 220ms spring-like lift with no continuous animation" },
  { slug: "floating-color-orbs", title: "Floating Color Orbs", category: "backgrounds", tags: ["orbs", "ambient", "color"], difficulty: "intermediate", visual: "three solid pastel discs in cyan, pink, and purple floating on an otherwise white canvas without card gradients", interaction: "the discs drift along short independent paths and pause when reduced motion is requested", motion: "use 5–7 second ease-in-out loops, low travel distance, and alternate direction" },
  { slug: "page-curtain-transition", title: "Page Curtain Transition", category: "transitions", tags: ["page", "curtain", "route"], difficulty: "intermediate", visual: "a solid near-black curtain with a lime index badge sweeping across a white destination panel", interaction: "the curtain fully covers outgoing content before revealing the destination to avoid visual tearing", motion: "use 650ms cubic-bezier(0.76, 0, 0.24, 1) for both cover and reveal" },
  { slug: "shared-card-transition", title: "Shared Card Transition", category: "transitions", tags: ["shared-layout", "card", "detail"], difficulty: "advanced", visual: "a compact product tile expanding into a wider detail surface while its pink icon and title preserve identity", interaction: "selection grows the shared surface, relocates metadata, and keeps close controls reachable", motion: "use a layout spring at stiffness 260 damping 28 with a 120ms content crossfade" },
  { slug: "blur-swap-transition", title: "Blur Swap Transition", category: "transitions", tags: ["swap", "blur", "content"], difficulty: "beginner", visual: "two compact message states swapping inside a fixed white panel with a cyan status chip", interaction: "old content retreats while new content enters from the opposite side without changing panel height", motion: "use 220ms opacity and six-pixel translation; keep blur below four pixels" },
  { slug: "sticky-feature-stack", title: "Sticky Feature Stack", category: "scroll-effects", tags: ["sticky", "stack", "storytelling"], difficulty: "advanced", visual: "three editorial feature panels in white, lime, and near-black stacked within a compact scrolling viewport", interaction: "each panel pins briefly and scales down as the next panel overlaps, preserving native scrolling", motion: "map scroll progress to a scale range of 1 to 0.96 with no scrub delay" },
  { slug: "scroll-progress-timeline", title: "Scroll Progress Timeline", category: "scroll-effects", tags: ["timeline", "progress", "scroll"], difficulty: "intermediate", visual: "a slim vertical timeline with black milestones and a cyan progress line beside concise event labels", interaction: "the line fills as the internal content scrolls and active milestones gain a solid ring", motion: "smooth progress over 120ms while keeping the relationship directly tied to scroll position" },
  { slug: "parallax-caption-gallery", title: "Parallax Caption Gallery", category: "scroll-effects", tags: ["parallax", "gallery", "caption"], difficulty: "advanced", visual: "two solid-color editorial image blocks with oversized captions moving at a slightly different rate", interaction: "native scroll shifts captions by no more than 24 pixels and never hides essential text", motion: "use a direct scroll transform with clamped values and disable parallax for reduced motion" },
  { slug: "copy-success-toast", title: "Copy Success Toast", category: "misc", tags: ["toast", "copy", "feedback"], difficulty: "beginner", visual: "a near-black rounded toast with a lime check disc, concise success label, and muted keyboard hint", interaction: "the toast rises after copying, holds long enough to read, then exits without stealing focus", motion: "use a stiffness 360 damping 26 entrance, 1.8 second hold, and 180ms fade" },
  { slug: "animated-status-badge", title: "Animated Status Badge", category: "misc", tags: ["status", "badge", "presence"], difficulty: "beginner", visual: "a white status capsule with a green-lime dot, strong Available label, and an extremely soft outline", interaction: "the dot emits one restrained presence ring on mount and the entire badge responds to focus", motion: "use a 1.8 second low-opacity ring loop and disable the loop for reduced motion" },
  { slug: "radial-action-menu", title: "Radial Action Menu", category: "misc", tags: ["radial", "menu", "actions"], difficulty: "advanced", visual: "a black circular trigger surrounded by three pastel action buttons for save, share, and edit", interaction: "activation fans actions along a semicircle, supports Escape and outside click, and returns focus to the trigger", motion: "stagger actions by 45ms with stiffness 320 damping 24 and a 120ms trigger rotation" },
  { slug: "split-label-launch-button", title: "Split Label Launch Button", category: "buttons", tags: ["split-label", "cta", "launch"], difficulty: "intermediate", visual: "a near-black capsule split into a wide launch label and a compact lime arrow chamber by a quiet translucent divider", interaction: "hover widens the arrow chamber as the arrow travels diagonally, while press compresses both regions as one control", motion: "use a stiffness 320 damping 24 spring for chamber width and a 140ms press response", createdAt: "2026-07-14T13:30:00.000Z" },
  { slug: "cursor-reveal-case-study-card", title: "Cursor Reveal Case Study Card", category: "cards", tags: ["cursor", "reveal", "case-study"], difficulty: "advanced", visual: "a restrained editorial case-study card whose lemon evidence layer peeks through a movable circular viewing window", interaction: "pointer or keyboard focus reveals the evidence layer while the title and metric stay stable and readable", motion: "use a 220ms ease-out reveal, cap travel inside the card, and spring the window home at stiffness 280 damping 26", createdAt: "2026-07-14T13:30:00.000Z" },
  { slug: "elastic-tag-input", title: "Elastic Tag Input", category: "inputs", tags: ["tags", "chips", "keyboard"], difficulty: "intermediate", visual: "a white tag composer with cyan and lime chips, a compact text caret, and a calm helper label", interaction: "submitted tags settle with a small elastic pop, Backspace removes the last empty chip, and focus strengthens the shell", motion: "use stiffness 380 damping 22 for chip entry and a 160ms opacity exit", createdAt: "2026-07-14T13:30:00.000Z" },
  { slug: "sliding-rail-navigation", title: "Sliding Rail Navigation", category: "navigation", tags: ["rail", "tabs", "indicator"], difficulty: "intermediate", visual: "a slim vertical white navigation rail with a solid cyan active marker and concise monochrome labels", interaction: "selection slides the marker between rows without moving labels, with equivalent focus and arrow-key states", motion: "use a shared-layout spring at stiffness 340 damping 28 and a 120ms label color transition", createdAt: "2026-07-14T13:30:00.000Z" },
  { slug: "folding-square-loader", title: "Folding Square Loader", category: "loaders", tags: ["fold", "geometry", "progress"], difficulty: "intermediate", visual: "four small near-black squares folding across a lemon tile like a compact paper mechanism", interaction: "the deterministic loop communicates indeterminate progress without flashes, text shifts, or irregular timing", motion: "rotate each square 90 degrees over 720ms with 90ms stagger and a 1.6 second total loop", createdAt: "2026-07-14T13:30:00.000Z" },
  { slug: "editorial-line-mask-reveal", title: "Editorial Line Mask Reveal", category: "text-effects", tags: ["editorial", "mask", "headline"], difficulty: "intermediate", visual: "three oversized tightly tracked headline lines revealed from clean rectangular masks with one cyan punctuation mark", interaction: "lines rise in reading order on entry or replay and finish as ordinary selectable text", motion: "use 520ms cubic-bezier(0.22, 1, 0.36, 1) per line with 80ms stagger", createdAt: "2026-07-14T13:30:00.000Z" },
  { slug: "reactive-crosshair-field", title: "Reactive Crosshair Field", category: "backgrounds", tags: ["crosshair", "cursor", "grid"], difficulty: "advanced", visual: "an off-white technical field of sparse hairline crosses with one cyan coordinate marker and a small black readout", interaction: "the nearest cross responds to pointer or focus proximity while the decorative field never captures input", motion: "interpolate scale and opacity over 180ms, cap scale at 1.7, and keep the base field static", createdAt: "2026-07-14T13:30:00.000Z" },
  { slug: "stack-push-page-transition", title: "Stack Push Page Transition", category: "transitions", tags: ["stack", "page", "depth"], difficulty: "advanced", visual: "a white destination sheet pushing a near-black outgoing sheet backward with a small purple route badge", interaction: "the outgoing view scales down before the destination covers it, keeping both surfaces clipped to one stage", motion: "use a 620ms cubic-bezier(0.76, 0, 0.24, 1) push and a synchronized scale from 1 to 0.94", createdAt: "2026-07-14T13:30:00.000Z" },
  { slug: "scroll-pinned-number-story", title: "Scroll Pinned Number Story", category: "scroll-effects", tags: ["numbers", "sticky", "story"], difficulty: "advanced", visual: "oversized black chapter numbers pinned beside compact white editorial story cards with a lemon active accent", interaction: "native internal scrolling advances chapters while the number remains pinned and active content enters without scroll hijacking", motion: "map progress directly to 16px translation and opacity, with no scrub lag or momentum override", createdAt: "2026-07-14T13:30:00.000Z" },
  { slug: "undo-action-snackbar", title: "Undo Action Snackbar", category: "misc", tags: ["snackbar", "undo", "feedback"], difficulty: "beginner", visual: "a near-black rounded snackbar with a lime status disc, concise deletion message, and a high-contrast Undo action", interaction: "the message enters without stealing focus, Undo remains a real button, and dismissal never shifts surrounding layout", motion: "use a stiffness 360 damping 26 entrance, a stable four-second reading window, and a 180ms exit", createdAt: "2026-07-14T13:30:00.000Z" },
  { slug: "pressure-ring-button", title: "Pressure Ring Button", category: "buttons", tags: ["pressure", "ring", "hold"], difficulty: "intermediate", visual: "a black circular action nested inside a thin cyan progress ring on a quiet gray field", interaction: "pressing compresses the core and draws the ring clockwise while release springs both layers back without accidental activation", motion: "use a 700ms ring fill, a 120ms press scale, and stiffness 340 damping 24 for release", createdAt: "2026-07-14T14:00:00.000Z" },
  { slug: "foldout-pricing-card", title: "Foldout Pricing Card", category: "cards", tags: ["pricing", "foldout", "comparison"], difficulty: "advanced", visual: "a compact white pricing card with a lemon price tab and a concealed feature sheet offset behind it", interaction: "hover or focus unfolds the feature sheet sideways while price and call-to-action remain stable", motion: "use a 360ms ease-out width reveal and a stiffness 280 damping 26 card lift", createdAt: "2026-07-14T14:00:00.000Z" },
  { slug: "inline-validation-field", title: "Inline Validation Field", category: "inputs", tags: ["validation", "form", "feedback"], difficulty: "beginner", visual: "a clean email field whose compact status capsule changes from neutral to a lime valid state", interaction: "focus reveals guidance and a valid sample settles the status without changing field height or stealing focus", motion: "use a 180ms border transition and stiffness 360 damping 25 for the status check", createdAt: "2026-07-14T14:00:00.000Z" },
  { slug: "expandable-sidebar-markers", title: "Expandable Sidebar Markers", category: "navigation", tags: ["sidebar", "markers", "disclosure"], difficulty: "intermediate", visual: "a narrow near-black sidebar with three colored markers that expand into readable labels", interaction: "hover or keyboard focus expands one row without moving the rail, and active state remains distinguishable by shape", motion: "use a 260ms width transition with stiffness 300 damping 26 for marker movement", createdAt: "2026-07-14T14:00:00.000Z" },
  { slug: "breathing-type-loader", title: "Breathing Type Loader", category: "loaders", tags: ["typography", "breathing", "progress"], difficulty: "beginner", visual: "the word CREATING in bold black type with a single cyan period on an off-white tile", interaction: "letters breathe through restrained weight-like scale changes while remaining fully readable as a loading status", motion: "use a 1.4 second ease-in-out cycle with 55ms letter stagger and no blur", createdAt: "2026-07-14T14:00:00.000Z" },
  { slug: "wave-baseline-headline", title: "Wave Baseline Headline", category: "text-effects", tags: ["wave", "baseline", "headline"], difficulty: "intermediate", visual: "an oversized SIGNAL headline whose letters form a shallow cyan-accented baseline wave", interaction: "entry sends one wave across the letters before they settle on a common readable baseline", motion: "use 10px maximum vertical travel, 60ms stagger, and a stiffness 300 damping 22 spring", createdAt: "2026-07-14T14:00:00.000Z" },
  { slug: "editorial-margin-canvas", title: "Editorial Margin Canvas", category: "backgrounds", tags: ["editorial", "margin", "canvas"], difficulty: "beginner", visual: "a warm white editorial canvas with sparse hairline margins, registration numbers, and one solid pink annotation tab", interaction: "the annotation lifts on hover or focus while the structural background stays motionless", motion: "use a 220ms spring-like three-pixel lift and no continuous animation", createdAt: "2026-07-14T14:00:00.000Z" },
  { slug: "diagonal-block-transition", title: "Diagonal Block Transition", category: "transitions", tags: ["diagonal", "blocks", "page"], difficulty: "intermediate", visual: "three solid black, cyan, and lemon blocks sweeping diagonally across a white route stage", interaction: "blocks overlap enough to fully cover outgoing content before revealing a fixed destination label", motion: "use 520ms cubic-bezier(0.76, 0, 0.24, 1) sweeps with 70ms stagger", createdAt: "2026-07-14T14:00:00.000Z" },
  { slug: "horizontal-feature-chapters", title: "Horizontal Feature Chapters", category: "scroll-effects", tags: ["horizontal", "chapters", "scroll"], difficulty: "advanced", visual: "three wide editorial chapter panels arranged along a horizontal rail with a compact progress counter", interaction: "native horizontal scrolling reveals each panel with snap alignment and no wheel hijacking", motion: "use a 14px entry translation tied to viewport visibility and a 240ms ease-out settle", createdAt: "2026-07-14T14:00:00.000Z" },
  { slug: "presence-avatar-cluster", title: "Presence Avatar Cluster", category: "misc", tags: ["presence", "avatars", "collaboration"], difficulty: "beginner", visual: "four overlapping pastel avatar discs beside a white live-collaboration capsule and lime presence dot", interaction: "hover fans the avatars enough to reveal initials while focus exposes the same names accessibly", motion: "use 5px maximum separation, 45ms stagger, and stiffness 320 damping 24", createdAt: "2026-07-14T14:00:00.000Z" },
  { slug: "sliding-icon-cta", title: "Sliding Icon CTA", category: "buttons", tags: ["icon", "slide", "cta"], difficulty: "beginner", visual: "a white outlined capsule with a bold label and a solid orange arrow disc parked at its trailing edge", interaction: "hover or focus slides the arrow through the label track and swaps its direction without changing button width", motion: "use a stiffness 320 damping 24 spring for 18px travel and a 120ms press scale", createdAt: "2026-07-14T14:30:00.000Z" },
  { slug: "pinned-note-card", title: "Pinned Note Card", category: "cards", tags: ["note", "pin", "paper"], difficulty: "beginner", visual: "a lemon paper note with a black circular pin, subtle ruled lines, and a rotated pink priority tab", interaction: "hover lifts one lower corner and rocks the pin independently while keyboard focus shows the same emphasis", motion: "use a stiffness 280 damping 24 card spring and 180ms pin rotation", createdAt: "2026-07-14T14:30:00.000Z" },
  { slug: "voice-pulse-search-field", title: "Voice Pulse Search Field", category: "inputs", tags: ["voice", "search", "pulse"], difficulty: "intermediate", visual: "a broad white search field with a cyan microphone control and five compact audio bars", interaction: "activating voice mode changes the button label and animates deterministic bars while typed search remains available", motion: "use 700ms alternating bar loops with 45ms stagger and a 180ms control transition", createdAt: "2026-07-14T14:30:00.000Z" },
  { slug: "corner-command-dock", title: "Corner Command Dock", category: "navigation", tags: ["dock", "commands", "corner"], difficulty: "advanced", visual: "a compact near-black L-shaped dock with lime, cyan, and pink command tiles arranged around a central trigger", interaction: "hover or focus fans the command tiles from the corner while preserving at least 44px hit targets", motion: "use stiffness 330 damping 25 with 40ms stagger and 36px maximum travel", createdAt: "2026-07-14T14:30:00.000Z" },
  { slug: "domino-trail-loader", title: "Domino Trail Loader", category: "loaders", tags: ["domino", "trail", "progress"], difficulty: "intermediate", visual: "seven slim near-black dominoes crossing a soft gray tile with one cyan leading piece", interaction: "the pieces tip in a predictable wave and reset only after the final piece settles", motion: "use 420ms rotations with 80ms stagger inside a 1.7 second ease-in-out loop", createdAt: "2026-07-14T14:30:00.000Z" },
  { slug: "rolling-word-carousel", title: "Rolling Word Carousel", category: "text-effects", tags: ["words", "carousel", "mask"], difficulty: "intermediate", visual: "a fixed headline reading We build beside a lemon word window containing three tightly set nouns", interaction: "the word column rolls vertically through states while the surrounding sentence never shifts", motion: "use 480ms cubic-bezier(0.22, 1, 0.36, 1) vertical changes and a 1.2 second hold", createdAt: "2026-07-14T14:30:00.000Z" },
  { slug: "floating-sticker-canvas", title: "Floating Sticker Canvas", category: "backgrounds", tags: ["stickers", "canvas", "ambient"], difficulty: "intermediate", visual: "an off-white canvas with four solid pastel sticker shapes, black registration text, and ample negative space", interaction: "each sticker lifts and rotates slightly on pointer or keyboard focus without blocking foreground content", motion: "use independent 4–7 second low-distance drift and a 220ms interactive lift", createdAt: "2026-07-14T14:30:00.000Z" },
  { slug: "index-stamp-route-transition", title: "Index Stamp Route Transition", category: "transitions", tags: ["index", "stamp", "route"], difficulty: "intermediate", visual: "an oversized black route index stamping onto a white stage before a pink destination sheet reveals", interaction: "the index establishes destination context, then scales away as content becomes available", motion: "use a stiffness 300 damping 24 stamp, 180ms hold, and 420ms sheet reveal", createdAt: "2026-07-14T14:30:00.000Z" },
  { slug: "scroll-activated-comparison", title: "Scroll Activated Comparison", category: "scroll-effects", tags: ["comparison", "scroll", "split"], difficulty: "advanced", visual: "a split comparison surface with neutral Before content and a cyan After panel inside a native scrolling viewport", interaction: "scrolling advances a vertical divider and updates the visible metric without intercepting wheel or touch input", motion: "map scroll progress directly to a 20–80% divider range with a 120ms smoothing window", createdAt: "2026-07-14T14:30:00.000Z" },
  { slug: "expandable-help-beacon", title: "Expandable Help Beacon", category: "misc", tags: ["help", "beacon", "disclosure"], difficulty: "intermediate", visual: "a lime question-mark beacon that expands into a near-black help capsule with two concise actions", interaction: "click, focus, or hover reveals actions; Escape and outside click should close it and restore focus in production", motion: "use stiffness 340 damping 26 for width and 45ms stagger for action labels", createdAt: "2026-07-14T14:30:00.000Z" },
];

const accentByCategory: Record<Category, string> = {
  buttons: "#d8f34e",
  cards: "#53e8d4",
  inputs: "#f5e642",
  navigation: "#d8f34e",
  loaders: "#ff9950",
  "text-effects": "#53e8d4",
  backgrounds: "#f5c9d4",
  transitions: "#c5bff0",
  "scroll-effects": "#53e8d4",
  misc: "#d8f34e",
};

function makePrompt(seed: Seed) {
  return `Create a production-ready ${seed.title} component using React, Tailwind CSS, and Framer Motion. The visual direction is ${seed.visual}. Keep the composition aligned with a premium light-theme SaaS dashboard: use a white or #F4F5F6 surface, #111111 primary text, #4A4A4F supporting text, 20–24px corner radii, a one-pixel #ECECEE border where separation is needed, and only an extremely soft shadow. Do not add card gradients, default blue links, heavy shadows, or decorative clutter.

The interaction must work as follows: ${seed.interaction}. Implement motion precisely: ${seed.motion}. Animate transform and opacity whenever possible to avoid layout thrashing. The effect should start in a meaningful static state during server rendering, replay cleanly when remounted, and avoid infinite animation unless the pattern is explicitly a loader or ambient background. Use Framer Motion variants where multiple children coordinate, and keep state local to the component.

Make the component responsive from a 320px viewport through desktop widths. It must remain legible inside a compact preview card and expand naturally in a larger detail preview without fixed page-level positioning. Use fluid spacing, clamp oversized typography when appropriate, and keep touch targets at least 44 by 44 pixels. Do not depend on remote images, external CSS, network requests, random values, timers that are never cleaned up, or framework-specific server APIs.

Meet accessibility requirements: use semantic HTML, an explicit accessible name for icon-only controls, visible keyboard focus, logical tab order, sufficient text contrast, and appropriate ARIA only when native semantics are insufficient. Respect prefers-reduced-motion by replacing large movement with a short opacity change or a stable final state. Return a self-contained TypeScript React component that can be pasted into a Next.js client component, followed by any minimal usage example needed to reproduce the preview accurately.`;
}

function makeDemo(seed: Seed, index: number) {
  const accent = accentByCategory[seed.category];
  const secondary = ["#53e8d4", "#ff9950", "#c5bff0", "#f5c9d4"][index % 4];
  const base = `fontFamily: "Inter, sans-serif", color: "#111", boxSizing: "border-box"`;

  const customDemos: Record<string, string> = {
    "split-label-launch-button": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:190,background:"#f4f5f6",borderRadius:20}}><motion.button aria-label="Launch project" whileHover="hover" whileTap={{scale:.95}} style={{display:"flex",alignItems:"stretch",padding:0,border:0,borderRadius:999,overflow:"hidden",background:"#111",color:"#fff",cursor:"pointer",boxShadow:"0 10px 28px rgba(0,0,0,.12)"}}><span style={{padding:"15px 20px",fontWeight:800}}>Launch project</span><motion.span variants={{hover:{width:64}}} transition={{type:"spring",stiffness:320,damping:24}} style={{display:"grid",placeItems:"center",width:52,background:"#d8f34e",color:"#111",fontSize:20,borderLeft:"1px solid rgba(255,255,255,.16)"}}>↗</motion.span></motion.button></div>)()`,
    "cursor-reveal-case-study-card": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:220,background:"#f4f5f6",borderRadius:20,padding:18}}><motion.article initial="rest" whileHover="hover" whileFocus="hover" tabIndex={0} style={{position:"relative",overflow:"hidden",width:"min(100%,310px)",padding:22,borderRadius:22,background:"#fff",border:"1px solid #ececee"}}><motion.div variants={{rest:{clipPath:"circle(0% at 82% 24%)"},hover:{clipPath:"circle(72% at 82% 24%)"}}} transition={{duration:.42,ease:[.22,1,.36,1]}} style={{position:"absolute",inset:0,background:"#f5e642"}} /><div style={{position:"relative",fontFamily:"Inter, sans-serif"}}><span style={{fontSize:11,fontWeight:800,letterSpacing:1.2}}>CASE 04</span><h3 style={{fontSize:28,letterSpacing:-1.2,margin:"54px 0 8px"}}>Conversion system</h3><strong style={{fontSize:48,letterSpacing:-2}}>+38%</strong></div></motion.article></div>)()`,
    "elastic-tag-input": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:200,background:"#f4f5f6",borderRadius:20,padding:20}}><motion.div whileFocus={{scale:1.01}} style={{width:"min(100%,340px)",padding:16,borderRadius:20,background:"#fff",border:"1px solid #ececee",fontFamily:"Inter, sans-serif"}}><span style={{display:"block",fontSize:11,fontWeight:800,marginBottom:10}}>TEAM SKILLS</span><div style={{display:"flex",flexWrap:"wrap",gap:7}}>{["Motion","React","A11y"].map((tag,i)=><motion.button key={tag} initial={{scale:.7,opacity:0}} animate={{scale:1,opacity:1}} transition={{type:"spring",stiffness:380,damping:22,delay:i*.07}} aria-label={"Remove "+tag} style={{border:0,borderRadius:999,padding:"8px 10px",background:i===1?"#d8f34e":"#53e8d4",fontWeight:750}}>{tag} ×</motion.button>)}<input aria-label="Add a tag" placeholder="Add tag…" style={{minWidth:82,flex:1,border:0,outline:0,fontSize:14}} /></div></motion.div></div>)()`,
    "sliding-rail-navigation": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:220,background:"#f4f5f6",borderRadius:20}}><nav aria-label="Section navigation" style={{display:"grid",gap:5,width:190,padding:8,borderRadius:20,background:"#fff",boxShadow:"0 8px 24px rgba(0,0,0,.06)"}}>{["Overview","Signals","Archive"].map((item,i)=><motion.button key={item} whileHover={{x:3}} style={{position:"relative",display:"flex",alignItems:"center",gap:12,border:0,borderRadius:14,padding:"11px 13px",background:i===1?"#f4f5f6":"transparent",fontWeight:700,textAlign:"left"}}>{i===1?<motion.span layoutId="rail" style={{width:5,height:24,borderRadius:99,background:"#53e8d4"}} />:<span style={{width:5}} />}{item}</motion.button>)}</nav></div>)()`,
    "folding-square-loader": `(() => <div role="status" aria-label="Loading" style={{display:"grid",placeItems:"center",height:"100%",minHeight:200,background:"#f5e642",borderRadius:20}}><div style={{display:"grid",gridTemplateColumns:"repeat(2,28px)",gap:5,perspective:180}}>{[0,1,2,3].map(i=><motion.span key={i} animate={{rotateX:[0,90,0],backgroundColor:["#111","#53e8d4","#111"]}} transition={{duration:1.6,repeat:Infinity,delay:i*.09,ease:[.22,1,.36,1]}} style={{width:28,height:28,borderRadius:6,background:"#111",transformOrigin:"bottom"}} />)}</div></div>)()`,
    "editorial-line-mask-reveal": `(() => <div style={{display:"grid",alignContent:"center",height:"100%",minHeight:220,padding:24,background:"#fff",borderRadius:20}}>{["IDEAS","BECOME","INTERFACES."].map((line,i)=><div key={line} style={{overflow:"hidden"}}><motion.div initial={{y:"110%"}} animate={{y:0}} transition={{duration:.52,delay:i*.08,ease:[.22,1,.36,1]}} style={{fontFamily:"Inter, sans-serif",fontSize:"clamp(30px,7vw,55px)",fontWeight:850,lineHeight:.92,letterSpacing:-2,color:i===2?"#53e8d4":"#111"}}>{line}</motion.div></div>)}</div>)()`,
    "reactive-crosshair-field": `(() => <div style={{position:"relative",display:"grid",gridTemplateColumns:"repeat(8,1fr)",gap:16,alignContent:"center",height:"100%",minHeight:220,padding:22,overflow:"hidden",background:"#f7f7f3",borderRadius:20}}>{Array.from({length:48},(_,i)=><motion.span key={i} whileHover={{scale:1.7,rotate:90,color:"#53e8d4"}} style={{color:i===29?"#53e8d4":"#c8c9c5",fontSize:16,textAlign:"center"}}>+</motion.span>)}<span style={{position:"absolute",right:18,bottom:16,padding:"6px 9px",borderRadius:9,background:"#111",color:"#fff",font:"700 10px monospace"}}>X 48 · Y 21</span></div>)()`,
    "stack-push-page-transition": `(() => <div style={{position:"relative",height:"100%",minHeight:220,overflow:"hidden",background:"#d9d9dd",borderRadius:20,perspective:500}}><motion.div animate={{scale:[1,.94,1],y:[0,8,0]}} transition={{duration:2.4,repeat:Infinity,ease:[.76,0,.24,1]}} style={{position:"absolute",inset:12,display:"grid",placeItems:"center",borderRadius:18,background:"#111",color:"#fff",font:"800 24px Inter"}}>Archive</motion.div><motion.div animate={{x:["105%","105%","0%","0%","105%"]}} transition={{duration:2.4,repeat:Infinity,times:[0,.18,.48,.82,1],ease:[.76,0,.24,1]}} style={{position:"absolute",inset:12,display:"grid",placeItems:"center",borderRadius:18,background:"#fff",font:"800 24px Inter",boxShadow:"-12px 0 30px rgba(0,0,0,.12)"}}>Next route <span style={{padding:"6px 9px",borderRadius:99,background:"#c5bff0",fontSize:11}}>02</span></motion.div></div>)()`,
    "scroll-pinned-number-story": `(() => <div style={{height:230,overflowY:"auto",background:"#f4f5f6",borderRadius:20,padding:14}}>{["Frame the need","Shape the system","Ship the detail"].map((text,i)=><section key={text} style={{display:"grid",gridTemplateColumns:"72px 1fr",gap:10,minHeight:150,marginBottom:12}}><strong style={{position:"sticky",top:14,alignSelf:"start",font:"850 52px Inter",letterSpacing:-3}}>0{i+1}</strong><motion.div whileInView={{y:0,opacity:1}} initial={{y:16,opacity:.5}} viewport={{amount:.7}} style={{padding:18,borderRadius:20,background:i===1?"#f5e642":"#fff",font:"700 20px Inter"}}>{text}<p style={{fontSize:12,fontWeight:500,color:"#5f5f65",lineHeight:1.5}}>A focused chapter that preserves native scrolling.</p></motion.div></section>)}</div>)()`,
    "undo-action-snackbar": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:200,background:"#f4f5f6",borderRadius:20}}><motion.div role="status" initial={{y:20,opacity:0,scale:.94}} animate={{y:0,opacity:1,scale:1}} transition={{type:"spring",stiffness:360,damping:26}} style={{display:"flex",alignItems:"center",gap:12,padding:"11px 12px",borderRadius:18,background:"#111",color:"#fff",fontFamily:"Inter, sans-serif",boxShadow:"0 12px 30px rgba(0,0,0,.14)"}}><span style={{display:"grid",placeItems:"center",width:30,height:30,borderRadius:99,background:"#d8f34e",color:"#111",fontWeight:900}}>✓</span><span style={{fontSize:13}}>Item archived</span><button style={{minHeight:40,border:0,borderRadius:999,padding:"0 13px",background:"#d8f34e",fontWeight:800}}>Undo</button></motion.div></div>)()`,
    "pressure-ring-button": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:210,background:"#f4f5f6",borderRadius:20}}><motion.button aria-label="Hold to publish" whileHover="ready" whileTap={{scale:.9}} style={{position:"relative",display:"grid",placeItems:"center",width:94,height:94,borderRadius:99,border:"2px solid #53e8d4",background:"transparent"}}><motion.span variants={{ready:{scale:1.08}}} transition={{type:"spring",stiffness:340,damping:24}} style={{display:"grid",placeItems:"center",width:72,height:72,borderRadius:99,background:"#111",color:"#fff",fontWeight:800}}>Hold</motion.span><motion.span variants={{ready:{rotate:360}}} transition={{duration:.7}} style={{position:"absolute",top:-4,width:10,height:10,borderRadius:99,background:"#53e8d4"}} /></motion.button></div>)()`,
    "foldout-pricing-card": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:230,background:"#f4f5f6",borderRadius:20,padding:18}}><motion.article initial="rest" whileHover="open" whileFocus="open" tabIndex={0} style={{display:"flex",width:"min(100%,330px)",fontFamily:"Inter, sans-serif"}}><div style={{zIndex:1,width:190,padding:20,borderRadius:22,background:"#fff",border:"1px solid #ececee"}}><small>PRO</small><strong style={{display:"block",fontSize:42,marginTop:28}}>$24</strong><span style={{fontSize:12,color:"#666"}}>per workspace</span></div><motion.div variants={{rest:{width:22,x:-18,opacity:.4},open:{width:140,x:-8,opacity:1}}} transition={{duration:.36,ease:[.22,1,.36,1]}} style={{overflow:"hidden",padding:"20px 14px",borderRadius:"0 22px 22px 0",background:"#f5e642",whiteSpace:"nowrap",fontSize:12,fontWeight:700}}>✓ Unlimited drafts<br/><br/>✓ Shared library</motion.div></motion.article></div>)()`,
    "inline-validation-field": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:210,background:"#f4f5f6",borderRadius:20,padding:20}}><label style={{width:"min(100%,340px)",fontFamily:"Inter, sans-serif"}}><span style={{fontSize:11,fontWeight:800}}>WORK EMAIL</span><div style={{display:"flex",alignItems:"center",gap:8,marginTop:8,padding:"9px 10px 9px 15px",borderRadius:18,background:"#fff",border:"1px solid #dfe0e2"}}><input defaultValue="hello@studio.co" aria-describedby="email-status" style={{minWidth:0,flex:1,border:0,outline:0,fontSize:14}}/><motion.span id="email-status" initial={{scale:.7,opacity:0}} animate={{scale:1,opacity:1}} transition={{type:"spring",stiffness:360,damping:25}} style={{padding:"7px 9px",borderRadius:99,background:"#d8f34e",fontSize:11,fontWeight:800}}>✓ Valid</motion.span></div></label></div>)()`,
    "expandable-sidebar-markers": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:230,background:"#f4f5f6",borderRadius:20}}><nav aria-label="Workspace" style={{display:"grid",gap:7,padding:8,borderRadius:20,background:"#111"}}>{[["●","Boards","#d8f34e"],["◆","Signals","#53e8d4"],["■","Files","#f5c9d4"]].map(([icon,label,color])=><motion.button key={label} initial="rest" whileHover="open" whileFocus="open" style={{display:"flex",alignItems:"center",gap:10,minHeight:44,border:0,borderRadius:14,padding:"0 13px",background:"transparent",color:"#fff",overflow:"hidden"}}><span style={{color}}>{icon}</span><motion.span variants={{rest:{width:0,opacity:0},open:{width:62,opacity:1}}} transition={{duration:.26}} style={{overflow:"hidden",fontWeight:700,textAlign:"left"}}>{label}</motion.span></motion.button>)}</nav></div>)()`,
    "breathing-type-loader": `(() => { const word="CREATING".split(""); return <div role="status" aria-label="Creating" style={{display:"grid",placeItems:"center",height:"100%",minHeight:200,background:"#f7f7f3",borderRadius:20}}><div style={{display:"flex",fontFamily:"Inter, sans-serif"}}>{word.map((char,i)=><motion.span key={i} animate={{scaleY:[1,1.16,1],opacity:[.55,1,.55]}} transition={{duration:1.4,repeat:Infinity,delay:i*.055,ease:"easeInOut"}} style={{fontSize:"clamp(25px,6vw,44px)",fontWeight:850,letterSpacing:-2}}>{char}</motion.span>)}<span style={{fontSize:40,fontWeight:900,color:"#53e8d4"}}>.</span></div></div>; })()`,
    "wave-baseline-headline": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:210,background:"#fff",borderRadius:20}}><div aria-label="Signal" style={{display:"flex",alignItems:"baseline"}}>{"SIGNAL".split("").map((char,i)=><motion.span aria-hidden key={i} initial={{y:i%2?10:-10,opacity:.3}} animate={{y:0,opacity:1}} transition={{type:"spring",stiffness:300,damping:22,delay:i*.06}} style={{font:"850 clamp(38px,8vw,66px) Inter",letterSpacing:-4,color:i===3?"#53e8d4":"#111"}}>{char}</motion.span>)}</div></div>)()`,
    "editorial-margin-canvas": `(() => <div style={{position:"relative",height:"100%",minHeight:230,overflow:"hidden",background:"#faf9f4",borderRadius:20,border:"1px solid #ece9df"}}><span style={{position:"absolute",left:42,top:0,bottom:0,borderLeft:"1px solid #d8d5cb"}}/><span style={{position:"absolute",left:0,right:0,top:48,borderTop:"1px solid #d8d5cb"}}/><span style={{position:"absolute",left:12,top:14,font:"700 10px monospace",color:"#777"}}>M–04 / 128</span><motion.button whileHover={{y:-3,rotate:-1}} whileFocus={{y:-3}} style={{position:"absolute",right:24,bottom:25,width:150,padding:16,border:0,borderRadius:16,background:"#f5c9d4",fontWeight:800,textAlign:"left",boxShadow:"0 8px 20px rgba(0,0,0,.06)"}}>A margin for<br/>better ideas.</motion.button></div>)()`,
    "diagonal-block-transition": `(() => <div style={{position:"relative",height:"100%",minHeight:220,overflow:"hidden",background:"#fff",borderRadius:20}}><div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",font:"800 26px Inter"}}>Destination 03</div>{["#111","#53e8d4","#f5e642"].map((color,i)=><motion.span key={color} initial={{x:"-130%",skewX:-12}} animate={{x:["-130%","0%","130%"]}} transition={{duration:1.7,repeat:Infinity,repeatDelay:.7,delay:i*.07,ease:[.76,0,.24,1]}} style={{position:"absolute",inset:-20,background:color}}/>)}</div>)()`,
    "horizontal-feature-chapters": `(() => <div style={{height:230,overflowX:"auto",display:"flex",gap:12,padding:14,scrollSnapType:"x mandatory",background:"#f4f5f6",borderRadius:20}}>{["Discover","Compose","Deliver"].map((title,i)=><motion.section key={title} initial={{x:14,opacity:.65}} whileInView={{x:0,opacity:1}} viewport={{amount:.65}} style={{flex:"0 0 82%",scrollSnapAlign:"center",padding:20,borderRadius:20,background:i===1?"#53e8d4":i===2?"#111":"#fff",color:i===2?"#fff":"#111",fontFamily:"Inter, sans-serif"}}><small>0{i+1} / 03</small><h3 style={{marginTop:72,fontSize:30,letterSpacing:-1.5}}>{title}</h3></motion.section>)}</div>)()`,
    "presence-avatar-cluster": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:200,background:"#f4f5f6",borderRadius:20}}><motion.div initial="rest" whileHover="open" whileFocus="open" tabIndex={0} aria-label="4 collaborators online" style={{display:"flex",alignItems:"center",padding:10,borderRadius:999,background:"#fff",boxShadow:"0 8px 24px rgba(0,0,0,.06)"}}><div style={{display:"flex"}}>{[["AL","#53e8d4"],["MK","#f5c9d4"],["JS","#c5bff0"],["+2","#d8f34e"]].map(([name,color],i)=><motion.span key={name} variants={{rest:{x:-i*8},open:{x:i*2}}} transition={{type:"spring",stiffness:320,damping:24,delay:i*.045}} style={{display:"grid",placeItems:"center",width:38,height:38,borderRadius:99,background:color,border:"2px solid #fff",fontSize:11,fontWeight:800}}>{name}</motion.span>)}</div><span style={{margin:"0 10px",font:"700 12px Inter"}}>Live <b style={{color:"#79a800"}}>●</b></span></motion.div></div>)()`,
    "sliding-icon-cta": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:190,background:"#f4f5f6",borderRadius:20}}><motion.button initial="rest" whileHover="hover" whileFocus="hover" whileTap={{scale:.96}} style={{position:"relative",width:210,height:56,border:"1px solid #d9d9dc",borderRadius:999,background:"#fff",fontWeight:800,overflow:"hidden"}}><span>Explore patterns</span><motion.span variants={{rest:{x:0},hover:{x:-150,rotate:-45}}} transition={{type:"spring",stiffness:320,damping:24}} style={{position:"absolute",right:5,top:5,display:"grid",placeItems:"center",width:46,height:46,borderRadius:99,background:"#ff9950",fontSize:20}}>↗</motion.span></motion.button></div>)()`,
    "pinned-note-card": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:230,background:"#f4f5f6",borderRadius:20}}><motion.article whileHover={{y:-4,rotate:-2}} whileFocus={{y:-4,rotate:-2}} tabIndex={0} transition={{type:"spring",stiffness:280,damping:24}} style={{position:"relative",width:220,minHeight:150,padding:24,borderRadius:4,background:"#f5e642",fontFamily:"Inter, sans-serif",boxShadow:"0 12px 24px rgba(0,0,0,.08)"}}><motion.span whileHover={{rotate:14}} style={{position:"absolute",left:"50%",top:-10,width:24,height:24,borderRadius:99,background:"#111"}}/><small style={{fontWeight:800}}>TODAY / 04</small><h3 style={{margin:"42px 0 8px",fontSize:25,letterSpacing:-1}}>Refine the final 10%.</h3><span style={{position:"absolute",right:-8,bottom:18,padding:"6px 9px",background:"#f5c9d4",fontSize:10,fontWeight:800,transform:"rotate(5deg)"}}>HIGH</span></motion.article></div>)()`,
    "voice-pulse-search-field": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:210,background:"#f4f5f6",borderRadius:20,padding:18}}><div style={{display:"flex",alignItems:"center",gap:10,width:"min(100%,360px)",padding:9,borderRadius:999,background:"#fff",border:"1px solid #ececee"}}><span style={{marginLeft:8}}>⌕</span><input aria-label="Search" placeholder="Search by voice…" style={{minWidth:0,flex:1,border:0,outline:0,fontSize:14}}/><motion.button aria-label="Start voice search" whileTap={{scale:.93}} style={{display:"flex",alignItems:"center",gap:3,minWidth:60,height:44,border:0,borderRadius:99,background:"#53e8d4",justifyContent:"center"}}>{[12,22,16,28,14].map((h,i)=><motion.span key={i} animate={{height:[6,h,6]}} transition={{duration:.7,repeat:Infinity,delay:i*.045}} style={{width:3,height:6,borderRadius:9,background:"#111"}}/>)}</motion.button></div></div>)()`,
    "corner-command-dock": `(() => <div style={{position:"relative",height:"100%",minHeight:230,background:"#f4f5f6",borderRadius:20}}><motion.nav initial="rest" whileHover="open" whileFocus="open" tabIndex={0} aria-label="Quick commands" style={{position:"absolute",left:28,bottom:24,width:58,height:58,borderRadius:18,background:"#111"}}>{[[36,-46,"S","#d8f34e"],[76,-5,"N","#53e8d4"],[72,-48,"⌘","#f5c9d4"]].map(([x,y,label,color],i)=><motion.button key={label} variants={{rest:{x:5,y:5,scale:.5,opacity:0},open:{x,y,scale:1,opacity:1}}} transition={{type:"spring",stiffness:330,damping:25,delay:i*.04}} style={{position:"absolute",left:5,top:5,width:48,height:48,border:0,borderRadius:15,background:color,fontWeight:900}}>{label}</motion.button>)}<span style={{display:"grid",placeItems:"center",height:"100%",color:"#fff",fontSize:22}}>＋</span></motion.nav></div>)()`,
    "domino-trail-loader": `(() => <div role="status" aria-label="Loading" style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,height:"100%",minHeight:200,background:"#f4f5f6",borderRadius:20,perspective:240}}>{[0,1,2,3,4,5,6].map((i)=><motion.span key={i} animate={{rotateZ:[0,58,0],y:[0,7,0]}} transition={{duration:1.7,repeat:Infinity,delay:i*.08,ease:"easeInOut"}} style={{width:12,height:48,borderRadius:5,background:i===0?"#53e8d4":"#111",transformOrigin:"bottom"}}/>)}</div>)()`,
    "rolling-word-carousel": `(() => <div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:10,height:"100%",minHeight:210,background:"#fff",borderRadius:20,fontFamily:"Inter, sans-serif",fontSize:"clamp(26px,6vw,44px)",fontWeight:850,letterSpacing:-2}}><span>We build</span><div style={{height:58,overflow:"hidden",padding:"0 10px",borderRadius:12,background:"#f5e642"}}><motion.div animate={{y:[0,0,-58,-58,-116,-116,0]}} transition={{duration:4.8,repeat:Infinity,times:[0,.22,.3,.52,.6,.85,1],ease:[.22,1,.36,1]}}>{["systems","motion","clarity"].map(w=><div key={w} style={{height:58,display:"flex",alignItems:"center"}}>{w}</div>)}</motion.div></div></div>)()`,
    "floating-sticker-canvas": `(() => <div style={{position:"relative",height:"100%",minHeight:230,overflow:"hidden",background:"#faf9f4",borderRadius:20}}><span style={{position:"absolute",left:16,top:14,font:"700 10px monospace"}}>CANVAS / 07</span>{[[24,62,70,46,"#53e8d4","IDEA"],[140,36,54,54,"#f5c9d4","✦"],[218,112,82,42,"#d8f34e","SHIP"],[94,146,46,46,"#c5bff0","↗"]].map(([x,y,w,h,c,t],i)=><motion.button key={t} animate={{y:[0,i%2?6:-6,0],rotate:[-2,2,-2]}} whileHover={{y:-5,scale:1.05}} transition={{duration:4+i,repeat:Infinity,ease:"easeInOut"}} style={{position:"absolute",left:x,top:y,width:w,height:h,border:0,borderRadius:i%2?99:12,background:c,fontWeight:900}}>{t}</motion.button>)}</div>)()`,
    "index-stamp-route-transition": `(() => <div style={{position:"relative",height:"100%",minHeight:220,overflow:"hidden",background:"#fff",borderRadius:20}}><motion.strong animate={{scale:[2.2,1,1,.75],opacity:[0,1,1,0]}} transition={{duration:2.2,repeat:Infinity,times:[0,.2,.55,.72],ease:[.22,1,.36,1]}} style={{position:"absolute",inset:0,display:"grid",placeItems:"center",font:"900 86px Inter",letterSpacing:-6}}>07</motion.strong><motion.div animate={{y:["105%","105%","0%","0%","105%"]}} transition={{duration:2.2,repeat:Infinity,times:[0,.52,.72,.9,1]}} style={{position:"absolute",inset:12,display:"grid",placeItems:"center",borderRadius:18,background:"#f5c9d4",font:"800 24px Inter"}}>Library index</motion.div></div>)()`,
    "scroll-activated-comparison": `(() => <div style={{height:230,overflowY:"auto",background:"#f4f5f6",borderRadius:20}}><div style={{height:430,padding:14}}><div style={{position:"sticky",top:14,height:200,overflow:"hidden",borderRadius:20,background:"#fff"}}><div style={{position:"absolute",inset:0,padding:22,fontFamily:"Inter, sans-serif"}}><small>BEFORE</small><strong style={{display:"block",marginTop:70,fontSize:38}}>42%</strong></div><motion.div whileInView={{width:"74%"}} initial={{width:"26%"}} viewport={{amount:.8}} transition={{duration:.5}} style={{position:"absolute",inset:"0 auto 0 0",overflow:"hidden",background:"#53e8d4",borderRight:"3px solid #111"}}><div style={{width:300,padding:22,fontFamily:"Inter, sans-serif"}}><small>AFTER</small><strong style={{display:"block",marginTop:70,fontSize:38}}>86%</strong></div></motion.div></div></div></div>)()`,
    "expandable-help-beacon": `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:200,background:"#f4f5f6",borderRadius:20}}><motion.div initial="rest" whileHover="open" whileFocus="open" tabIndex={0} style={{display:"flex",alignItems:"center",height:58,borderRadius:999,overflow:"hidden",background:"#111",color:"#fff"}}><span style={{display:"grid",placeItems:"center",width:58,height:58,borderRadius:99,background:"#d8f34e",color:"#111",fontSize:22,fontWeight:900}}>?</span><motion.div variants={{rest:{width:0,opacity:0},open:{width:190,opacity:1}}} transition={{type:"spring",stiffness:340,damping:26}} style={{display:"flex",alignItems:"center",gap:6,overflow:"hidden",whiteSpace:"nowrap"}}><span style={{marginLeft:12,fontSize:12,fontWeight:700}}>Need help?</span><button style={{minHeight:40,border:0,borderRadius:99,padding:"0 12px",background:"#53e8d4",fontWeight:800}}>Open guide</button></motion.div></motion.div></div>)()`,
  };

  if (customDemos[seed.slug]) return customDemos[seed.slug];

  switch (seed.category) {
    case "buttons":
      return `(() => { const isDark = ${index % 2 === 0}; return <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:180,background:"#f4f5f6",borderRadius:20}}><motion.button aria-label="${seed.title}" whileHover={{y:-3,scale:1.03}} whileTap={{scale:.94}} transition={{type:"spring",stiffness:300,damping:24}} style={{${base},position:"relative",overflow:"hidden",border:0,borderRadius:999,padding:"15px 24px",fontWeight:750,background:isDark?"#111":"${accent}",color:isDark?"#fff":"#111",boxShadow:"0 8px 24px rgba(0,0,0,.10)",cursor:"pointer"}}><motion.span aria-hidden animate={{scale:[1,1.45,1],opacity:[.75,.2,.75]}} transition={{duration:1.5,repeat:Infinity}} style={{display:"inline-block",width:8,height:8,borderRadius:99,marginRight:10,background:"${secondary}"}} />${seed.title.replace(" Button", "")}</motion.button></div>; })()`;
    case "cards":
      return `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:220,background:"#f7f7f8",borderRadius:20,padding:20}}><motion.article whileHover={{y:-4,rotate:${index % 2 ? -1.5 : 1.5}}} transition={{type:"spring",stiffness:300,damping:24}} style={{${base},width:"min(100%,300px)",padding:22,borderRadius:22,background:"#fff",border:"1px solid #ececee",boxShadow:"0 10px 30px rgba(0,0,0,.06)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:11,fontWeight:800,textTransform:"uppercase",letterSpacing:1.2}}>Featured</span><span style={{width:36,height:36,borderRadius:12,background:"${accent}"}} /></div><div style={{fontSize:${index % 2 ? 42 : 54},fontWeight:800,letterSpacing:-2,marginTop:24}}>${index % 2 ? "24.8K" : "86%"}</div><p style={{margin:"6px 0 18px",color:"#4a4a4f",fontSize:13}}>${seed.title}</p><div style={{display:"flex",gap:6,alignItems:"end",height:38}}>{[18,28,22,36,31].map((h,i)=><motion.span key={i} initial={{height:8}} animate={{height:h}} transition={{delay:i*.04,duration:.35}} style={{flex:1,borderRadius:8,background:i===4?"${accent}":"#e7e8ea"}} />)}</div></motion.article></div>)()`;
    case "inputs":
      return `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:200,background:"#f4f5f6",borderRadius:20,padding:22}}><motion.label whileFocus={{scale:1.01}} style={{${base},display:"block",width:"min(100%,340px)",padding:18,borderRadius:20,background:"#fff",border:"1px solid #ececee",boxShadow:"0 6px 20px rgba(0,0,0,.04)"}}><span style={{display:"block",fontSize:11,fontWeight:800,textTransform:"uppercase",letterSpacing:1.2,marginBottom:9,color:"#6b6b71"}}>${seed.title}</span><span style={{display:"flex",alignItems:"center",gap:9}}><span aria-hidden style={{width:10,height:10,borderRadius:99,background:"${accent}"}} /><input aria-label="${seed.title}" placeholder="Start typing…" style={{${base},width:"100%",border:0,outline:0,fontSize:16,background:"transparent"}} /><kbd style={{padding:"5px 8px",borderRadius:8,background:"#f4f5f6",fontSize:11,color:"#777"}}>⌘K</kbd></span><motion.span initial={{scaleX:0}} animate={{scaleX:1}} transition={{duration:.45}} style={{display:"block",height:2,marginTop:12,transformOrigin:"left",background:"${accent}",borderRadius:99}} /></motion.label></div>)()`;
    case "navigation":
      return `(() => { const items=["Home","Explore","Saved"]; return <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:180,background:"#f7f7f8",borderRadius:20}}><nav aria-label="Preview navigation" style={{${base},display:"flex",gap:6,padding:7,borderRadius:999,background:${index % 2 ? '"#111"' : '"#fff"'},boxShadow:"0 8px 24px rgba(0,0,0,.08)"}}>{items.map((item,i)=><motion.button key={item} whileHover={{y:-2,scale:1.04}} whileTap={{scale:.96}} style={{border:0,borderRadius:999,padding:"11px 15px",fontWeight:700,fontSize:12,background:i===${index % 3}?"${accent}":"transparent",color:${index % 2 ? 'i===' + (index % 3) + '?"#111":"#fff"' : '"#111"'},cursor:"pointer"}}>{item}</motion.button>)}</nav></div>; })()`;
    case "loaders":
      return index % 3 === 0
        ? `(() => <div role="status" aria-label="Loading" style={{display:"grid",placeItems:"center",height:"100%",minHeight:190,background:"#f4f5f6",borderRadius:20}}><motion.div animate={{rotate:360}} transition={{duration:1.4,repeat:Infinity,ease:"linear"}} style={{position:"relative",width:80,height:80,border:"1px solid #ddd",borderRadius:999}}>{["#53e8d4","#d8f34e","#ff9950"].map((c,i)=><span key={c} style={{position:"absolute",width:12,height:12,borderRadius:99,background:c,left:34,top:i*30-4,transform:"translateY(-50%)"}} />)}</motion.div><span style={{position:"absolute",width:18,height:18,borderRadius:99,background:"#111"}} /></div>)()`
        : `(() => <div role="status" aria-label="Loading" style={{display:"flex",alignItems:"center",justifyContent:"center",gap:7,height:"100%",minHeight:190,background:"${accent}",borderRadius:20}}>{[0,1,2,3,4].map(i=><motion.span key={i} animate={{height:[18,54,18]}} transition={{duration:.8,repeat:Infinity,delay:i*.07,ease:"easeInOut"}} style={{display:"block",width:9,height:18,borderRadius:99,background:i===2?"${secondary}":"#111"}} />)}<span className="sr-only">Loading</span></div>)()`;
    case "text-effects":
      return `(() => { const chars="${index % 2 ? "SIGNAL" : "BUILD"}".split(""); return <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:190,background:"#fff",borderRadius:20,overflow:"hidden"}}><div aria-label={chars.join("")} style={{${base},display:"flex",alignItems:"baseline"}}>{chars.map((char,i)=><motion.span aria-hidden key={i} initial={{y:44,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.42,delay:i*.045,ease:[.22,1,.36,1]}} style={{fontSize:"clamp(40px,9vw,74px)",fontWeight:850,letterSpacing:-4}}>{char}</motion.span>)}<span style={{fontSize:54,fontWeight:900,color:"${accent}"}}>.</span></div></div>; })()`;
    case "backgrounds":
      return index % 3 === 0
        ? `(() => <div style={{display:"grid",gridTemplateColumns:"repeat(12,1fr)",gap:12,alignContent:"center",height:"100%",minHeight:220,padding:24,background:"#fff",borderRadius:20}}>{Array.from({length:72},(_,i)=><motion.span key={i} whileHover={{scale:2,backgroundColor:"${accent}"}} style={{width:4,height:4,borderRadius:99,background:i%11===0?"${accent}":"#cfd0d2"}} />)}</div>)()`
        : `(() => <div style={{position:"relative",height:"100%",minHeight:220,overflow:"hidden",background:"#fff",borderRadius:20}}>{["${accent}","${secondary}","#d8f34e"].map((c,i)=><motion.span key={c} animate={{x:[0,(i-1)*24,0],y:[0,(1-i)*18,0]}} transition={{duration:5+i,repeat:Infinity,ease:"easeInOut"}} style={{position:"absolute",width:80+i*22,height:80+i*22,borderRadius:999,background:c,left:28+i*66,top:38+i*28,opacity:.78}} />)}<span style={{position:"absolute",left:24,bottom:22,fontFamily:"Inter, sans-serif",fontWeight:800,fontSize:22}}>Quiet motion.</span></div>)()`;
    case "transitions":
      return `(() => <div style={{position:"relative",height:"100%",minHeight:220,overflow:"hidden",background:"#f4f5f6",borderRadius:20}}><div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",${base},fontSize:26,fontWeight:800}}>New view <span style={{color:"${accent}"}}>02</span></div><motion.div initial={{x:"-102%"}} animate={{x:["-102%","0%","102%"]}} transition={{duration:1.8,repeat:Infinity,repeatDelay:.5,ease:[.76,0,.24,1]}} style={{position:"absolute",inset:0,display:"grid",placeItems:"center",background:"#111",color:"#fff",fontFamily:"Inter, sans-serif",fontWeight:800}}><span style={{padding:"8px 12px",borderRadius:999,background:"${accent}",color:"#111"}}>Transition</span></motion.div></div>)()`;
    case "scroll-effects":
      return `(() => <div aria-label="Scrollable effect preview" style={{height:230,overflowY:"auto",scrollbarWidth:"thin",background:"#f4f5f6",borderRadius:20,padding:14}}>{["Discover","Shape","Ship"].map((label,i)=><motion.section key={label} whileInView={{scale:1,opacity:1}} initial={{scale:.96,opacity:.65}} viewport={{amount:.7}} style={{${base},position:"sticky",top:12+i*10,minHeight:150,marginBottom:14,padding:20,borderRadius:20,background:i===1?"${accent}":i===2?"#111":"#fff",color:i===2?"#fff":"#111",boxShadow:"0 8px 24px rgba(0,0,0,.07)"}}><span style={{fontSize:11,textTransform:"uppercase",letterSpacing:1.3}}>0{i+1}</span><h3 style={{fontSize:32,margin:"34px 0 0",letterSpacing:-1.5}}>{label}</h3></motion.section>)}</div>)()`;
    case "misc":
      return `(() => <div style={{display:"grid",placeItems:"center",height:"100%",minHeight:200,background:"#f4f5f6",borderRadius:20}}><motion.div initial={{y:18,opacity:0,scale:.94}} animate={{y:0,opacity:1,scale:1}} transition={{type:"spring",stiffness:360,damping:26}} role="status" style={{${base},display:"flex",alignItems:"center",gap:12,padding:"12px 15px",borderRadius:18,background:${index % 2 ? '"#fff"' : '"#111"'},color:${index % 2 ? '"#111"' : '"#fff"'},boxShadow:"0 12px 30px rgba(0,0,0,.12)"}}><motion.span animate={{scale:[1,1.18,1]}} transition={{duration:1.8,repeat:Infinity}} style={{display:"grid",placeItems:"center",width:30,height:30,borderRadius:99,background:"${accent}",color:"#111",fontWeight:900}}>✓</motion.span><span><strong style={{display:"block",fontSize:13}}>${seed.title}</strong><small style={{color:${index % 2 ? '"#777"' : '"#b8b8bd"'}}}>Ready to use</small></span></motion.div></div>)()`;
  }
}

function makeReactCode(seed: Seed, demoCode: string) {
  const componentName = seed.slug
    .split("-")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");

  return `"use client";

import { motion } from "framer-motion";

export default function ${componentName}() {
  return ${demoCode};
}`;
}

function makeCss(seed: Seed) {
  const accent = accentByCategory[seed.category];
  const animationName = seed.slug.replaceAll("-", "_");
  return `/* Suggested markup: <div class="uiwiki-${seed.slug}" tabindex="0"><span>${seed.title}</span></div> */
.uiwiki-${seed.slug} {
  display: grid;
  place-items: center;
  min-height: 11rem;
  padding: 1.25rem;
  border: 1px solid #ececee;
  border-radius: 22px;
  background: #ffffff;
  color: #111111;
  font: 700 1rem/1.2 Inter, system-ui, sans-serif;
  box-shadow: 0 2px 16px rgba(0, 0, 0, 0.04);
  transition: transform 240ms cubic-bezier(.22, 1, .36, 1), box-shadow 240ms ease;
}
.uiwiki-${seed.slug} > span {
  padding: .75rem 1rem;
  border-radius: 999px;
  background: ${accent};
  animation: ${animationName} 1.8s ease-in-out infinite alternate;
}
.uiwiki-${seed.slug}:hover,
.uiwiki-${seed.slug}:focus-visible {
  transform: translateY(-3px);
  box-shadow: 0 10px 28px rgba(0, 0, 0, 0.08);
}
@keyframes ${animationName} {
  from { transform: translateY(0) scale(1); }
  to { transform: translateY(-4px) scale(1.025); }
}
@media (prefers-reduced-motion: reduce) {
  .uiwiki-${seed.slug}, .uiwiki-${seed.slug} > span { animation: none; transition: none; }
}`;
}

async function main() {
  const directory = path.join(process.cwd(), "content", "components");
  await mkdir(directory, { recursive: true });

  await Promise.all(
    seeds.map(async (seed, index) => {
      const demoCode = makeDemo(seed, index);
      const entry = componentEntrySchema.parse({
        slug: seed.slug,
        title: seed.title,
        category: seed.category,
        tags: seed.tags,
        difficulty: seed.difficulty,
        prompt: makePrompt(seed),
        code: {
          react: makeReactCode(seed, demoCode),
          css: makeCss(seed),
        },
        demoCode,
        source: "original",
        createdAt: seed.createdAt ?? "2026-07-13T00:00:00.000Z",
      });

      await writeFile(
        path.join(directory, `${seed.slug}.json`),
        `${JSON.stringify(entry, null, 2)}\n`,
        "utf8",
      );
    }),
  );

  const pool = await readIdeaPool();
  const seededSlugs = new Set(seeds.map((seed) => seed.slug));
  const usedAt = "2026-07-14T13:30:00.000Z";
  pool.ideas = pool.ideas.map((idea) =>
    idea.status === "available" && seededSlugs.has(idea.id)
      ? { ...idea, status: "used" as const, usedAt }
      : idea,
  );
  await writeIdeaPool(pool);

  console.log(`Seeded ${seeds.length} original component entries.`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
